import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { StarIcon } from "@heroicons/react/24/solid";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid h-screen place-items-center">
          <div className="bg-slate-700 rounded-2xl w-1/2 text-white">
            <div className="w-12 bg-slate-600 ml-4 mt-4 rounded-full p-2">
              <div>
                <StarIcon className="text-orange-500" />
              </div>
            </div>
            <div className="ml-4 mt-6">
              <h4 className="text-xl font-bold tracking-light mb-4">How did we do?</h4>
              <p className="text-thin text-slate-400">
                Please let us know how we did with your support request. All
                feedback is appreciated to help us improve our offering!
              </p>
            </div>
            <div className="space-x-4 ml-4 mt-6">
              <div className="bg-gray-500 w-12 h-12 rounded-full inline-flex items-center justify-center">1</div>
              <div className="bg-gray-500 w-12 h-12 rounded-full inline-flex items-center justify-center">2</div>
              <div className="bg-gray-500 w-12 h-12 rounded-full inline-flex items-center justify-center">3</div>
              <div className="bg-gray-500 w-12 h-12 rounded-full inline-flex items-center justify-center">4</div>
              <div className="bg-gray-500 w-12 h-12 rounded-full inline-flex items-center justify-center">5</div>
            </div>

  
              <div className="place-items-center grid mt-4 mb-3">
                <button on className="uppercase place-items-center grid block w-11/12 tracking-wide font-bold bg-orange-500 rounded-3xl text-white p-3 mt-4 mb-4">Submit</button>
              </div>
          </div>
        </div>
      </main>
    </>
  );
}
